name: Validation of WDL Script

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  miniwdl_check:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - 
      name: Install miniwdl
      run: |
        python -m pip install --upgrade pip
        pip3 install miniwdl
    - 
      name: Run miniwdl
      run: |
        EXITCODE=0
        echo "Checking WDL files using \`miniwdl check\`."
        files=$(find . -name '*.wdl')
        for file in $files; do
          echo "  [***] $file [***]"
          miniwdl check "$file"
          EXITCODE=$(($? || EXITCODE))
        done
        exit $EXITCODE

  womtoolval:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set Up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    -
      name: Pull WOMtool Jarfile
      run: wget -q https://github.com/broadinstitute/cromwell/releases/download/86/womtool-86.jar
    -
      name: WOMtool Validation
      run: java -jar womtool-86.jar validate *.wdl -i *-inputs.json

  sprocket-lint:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Set Up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - 
      name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
        key: ${{ runner.os }}-cargo-sprocket-0.12.2
        restore-keys: |
          ${{ runner.os }}-cargo-sprocket-
    - 
      name: Install Sprocket
      run: |
        # Check if sprocket is already available (from cache)
        if ! command -v sprocket &> /dev/null; then
          echo "Installing Sprocket 0.12.2..."
          cargo install sprocket --version 0.12.2
        else
          echo "Sprocket found in cache"
          sprocket --version
        fi
    - 
      name: Run Sprocket Linting
      run: |
        EXITCODE=0
        echo "Checking WDL files using Sprocket lint."
        files=$(find . -name '*.wdl')
        for file in $files; do
          echo "  [***] $file [***]"
          # Run with warnings and notes treated as errors
          sprocket lint "$file" --deny-warnings --deny-notes
          EXITCODE=$(($? || EXITCODE))
        done
        exit $EXITCODE
